### PR TITLE
fixed syntax error in windows-fix sh

### PR DESCRIPTION
**Pull request by DonShelly**
fixed syntax error in windows-fix sh

### CODE REVIEW

**Review by cyrusdobbs — DISMISSED** [review]
Tested and it works locally for me. Strange that it worked for me before, but not for you? Got slightly different set ups I guess?

Only thing is (bit picky I know..) it might be worth renaming the commit without the typos

**Comment by DonShelly** [comment]
> Tested and it works locally for me. Strange that it worked for me before, but not for you? Got slightly different set ups I guess?
> 
> Only thing is (bit picky I know..) it might be worth renaming the commit without the typos

done

**Comment by DonShelly** [comment]
> Doesn't look to have updated @DonShelly

think ive sorted it now?

**Comment by cyrusdobbs** [comment]
You've got 3 commits now

**Review by cyrusdobbs — APPROVED** [review]
LGTM 👍

**Pull request merged**
