### PR TITLE
Pull in `.env` file, auto-restart, and make interactive

### PR DESCRIPTION
**Pull request by samuelhwilliams**
### Change description
Pulls in config from the `.env` file, so that we can store secrets outside of git if needed.

Turns on auto-restart for data-store, find and submit, so that if they crash the container reboots automatically. Hopefully more pros than cons but we could drop this if it ends up annoying.

Opens stdin and enables tty mode, so that eg you can interactively debug via pdb/ipdb/pdbpp directly if you don't use remote debugging.

- [ ] README and other documentation has been updated / added (if needed)
- [ ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### How to test
_If manual testing is needed, give suggested testing steps_

### CODE REVIEW

**Review by wjrm500 — APPROVED** [review]
Looks fine to me. Adding `stdin_open` and `tty` will benefit you and whoever else uses PDB without any negative repercussions as far as I can tell (although, quick question: are there any specific reasons you are using PDB?), while the `restart` thing looks like it could be useful. I'm not sure on the need for the `env_file` change (at least without removing the `environment` property, because now we have environment variables coming from two different places, which could be confusing) but happy to approve nonetheless as I don't think it'll have any negative real-world effect at this point.

**Comment by samuelhwilliams** [comment]
`.env` lets us put in 'secret' values that aren't committed to this git repo, whereas `environment` in docker-compose will by its nature end up getting committed to this (public) repo.

**Comment by wjrm500** [comment]
> `.env` lets us put in 'secret' values that aren't committed to this git repo, whereas `environment` in docker-compose will by its nature end up getting committed to this (public) repo.
> 
> The `.env` file concept isn't really new I don't think - our README already talks about it. This is, I think, just hooking it up so it actually works? 😅

Sure it's just that I'm wondering whether we should migrate all env vars currently defined in the `docker-compose.yml` file into the `.env` file at this point so we don't have two sources of env vars?

**Comment by samuelhwilliams** [comment]
Yeah fair point - maybe.

I guess we'd need to namespace env vars then a bit more - because the `environment` blocks are per-service whereas we have a single `.env` file for all three apps with this approach.

I agree it's probably something to streamline in the near/mid future...

**Comment by samuelhwilliams** [comment]
As for why I use pdb natively ... just habit I think mostly - have always used it in the terminal rather than integrated IDE debuggers. I suspect it's mostly because I just never got it set up and working properly in pycharm. One of these days maybe I'll do it ...

**Pull request merged**
