### PR TITLE
[SMD-87] add resorce files for localstack development of funding spent

### PR DESCRIPTION
**Pull request by Connor-OS**
Adds an example grant awarded csv to the file assets bucket on local stack that can be accest during validation

### Change description
_A brief description of the pull request_ 

- [ ] README and other documentation has been updated / added (if needed)
- [ ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### How to test
_If manual testing is needed, give suggested testing steps_

### CODE REVIEW

**Review by bobbi-hbrown — APPROVED** [review]
LGTM

**Comment by bobbi-hbrown** [comment]
> LGTM
Sorry, I approved this initially as it does work when tested. However, there are some tests in the data store repo (tests.test_aws.test_list_buckets and tests.test_aws.test_extract_file_from_bucket) which reference these endpoints, so these will also need updating to reflect the new names

**Comment by Connor-OS** [comment]
> > Sorry, I approved this initially as it does work when tested. However, there are some tests in the data store repo (tests.test_aws.test_list_buckets and tests.test_aws.test_extract_file_from_bucket) which reference these endpoints, so these will also need updating to reflect the new names

No worries, I've updated the relevent tests in the data store PR that goes along with this

**Comment by Connor-OS** [comment]
> > LGTM
> > Sorry, I approved this initially as it does work when tested. However, there are some tests in the data store repo (tests.test_aws.test_list_buckets and tests.test_aws.test_extract_file_from_bucket) which reference these endpoints, so these will also need updating to reflect the new names

Thanks for pointing this out. I've changed it in here: https://github.com/communitiesuk/funding-service-design-post-award-data-store/pull/293/files

**Review by bobbi-hbrown — APPROVED** [review]

**Comment by bobbi-hbrown** [comment]
Looks good! May also be worth adding a note in the readme about the tests coupled to it in the data store if you think it may be useful :)

**Pull request merged**
